# Copyright 2021 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ahmadapp-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ahmadapp
      role: frontend
      env: production
  template:
    metadata:
      name: frontend
      labels:
        app: ahmadapp
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/devops-analiza/ahmadapp:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: frontend
          containerPort: 3080
        env:
          - name: PORT
            value: "3080"

---

apiVersion: v1
kind: Service
metadata:
  name: ahmadapp-production
  labels:
    run: ahmadapp
spec:
  ports:
  - port: 3080
    protocol: TCP
    name: "3080"
  - port: 443
    targetPort: 443
    name: "https"
  - port: 80
    targetPort: 80
    name: "http"
  selector:
    app: ahmadapp
  type: LoadBalancer